// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type AttachActivityRequest struct {
	// Activity Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Comma-separated list of entities which the activity primarily concerns
	Entities []string `queryParam:"style=form,explode=false,name=entities"`
}

func (a *AttachActivityRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AttachActivityRequest) GetEntities() []string {
	if a == nil {
		return nil
	}
	return a.Entities
}

type AttachActivityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	BaseActivityItem *shared.BaseActivityItem
	// The requested resource was not found
	NotFoundError *shared.NotFoundError
	// Too many requests
	TooManyRequestsError *shared.TooManyRequestsError
	Headers              map[string][]string
}

func (a *AttachActivityResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AttachActivityResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AttachActivityResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AttachActivityResponse) GetBaseActivityItem() *shared.BaseActivityItem {
	if a == nil {
		return nil
	}
	return a.BaseActivityItem
}

func (a *AttachActivityResponse) GetNotFoundError() *shared.NotFoundError {
	if a == nil {
		return nil
	}
	return a.NotFoundError
}

func (a *AttachActivityResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if a == nil {
		return nil
	}
	return a.TooManyRequestsError
}

func (a *AttachActivityResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
