// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type BulkMergeClassificationsRequestBody struct {
	// Job ID for tracking the status of a bulk operation request
	JobID                *string  `json:"job_id,omitempty"`
	TargetClassification *string  `json:"target_classification,omitempty"`
	ClassificationIds    []string `json:"classification_ids,omitempty"`
}

func (b *BulkMergeClassificationsRequestBody) GetJobID() *string {
	if b == nil {
		return nil
	}
	return b.JobID
}

func (b *BulkMergeClassificationsRequestBody) GetTargetClassification() *string {
	if b == nil {
		return nil
	}
	return b.TargetClassification
}

func (b *BulkMergeClassificationsRequestBody) GetClassificationIds() []string {
	if b == nil {
		return nil
	}
	return b.ClassificationIds
}

type BulkMergeClassificationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns the job id for the async job and current status
	TaxonomyBulkJobTriggerResponse *shared.TaxonomyBulkJobTriggerResponse
	// Too many requests
	TooManyRequestsError *shared.TooManyRequestsError
	Headers              map[string][]string
}

func (b *BulkMergeClassificationsResponse) GetContentType() string {
	if b == nil {
		return ""
	}
	return b.ContentType
}

func (b *BulkMergeClassificationsResponse) GetStatusCode() int {
	if b == nil {
		return 0
	}
	return b.StatusCode
}

func (b *BulkMergeClassificationsResponse) GetRawResponse() *http.Response {
	if b == nil {
		return nil
	}
	return b.RawResponse
}

func (b *BulkMergeClassificationsResponse) GetTaxonomyBulkJobTriggerResponse() *shared.TaxonomyBulkJobTriggerResponse {
	if b == nil {
		return nil
	}
	return b.TaxonomyBulkJobTriggerResponse
}

func (b *BulkMergeClassificationsResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if b == nil {
		return nil
	}
	return b.TooManyRequestsError
}

func (b *BulkMergeClassificationsResponse) GetHeaders() map[string][]string {
	if b == nil {
		return map[string][]string{}
	}
	return b.Headers
}
