// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type CreateSchemaGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	EntitySchemaGroupWithCompositeID *shared.EntitySchemaGroupWithCompositeID
	// Too many requests
	TooManyRequestsError *shared.TooManyRequestsError
	Headers              map[string][]string
}

func (c *CreateSchemaGroupResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateSchemaGroupResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateSchemaGroupResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateSchemaGroupResponse) GetEntitySchemaGroupWithCompositeID() *shared.EntitySchemaGroupWithCompositeID {
	if c == nil {
		return nil
	}
	return c.EntitySchemaGroupWithCompositeID
}

func (c *CreateSchemaGroupResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if c == nil {
		return nil
	}
	return c.TooManyRequestsError
}

func (c *CreateSchemaGroupResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
