// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type CreateEntityRequest struct {
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
	// Activity to include in event feed
	ActivityID *shared.ActivityIDQueryParam `queryParam:"style=form,explode=true,name=activity_id"`
	// Update the diff and entity for the custom activity included in the query.
	// Pending state on activity is automatically ended when activity is filled.
	//
	FillActivity *bool `default:"false" queryParam:"style=form,explode=true,name=fill_activity"`
	// Don't wait for updated entity to become available in Search API. Useful for large migrations
	Async *bool `default:"false" queryParam:"style=form,explode=true,name=async"`
	// When true, enables entity validation against the entity schema.
	Validate *bool               `default:"false" queryParam:"style=form,explode=true,name=validate"`
	Entity   *shared.EntityInput `request:"mediaType=application/json"`
}

func (c CreateEntityRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEntityRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"slug"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateEntityRequest) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

func (c *CreateEntityRequest) GetActivityID() *shared.ActivityIDQueryParam {
	if c == nil {
		return nil
	}
	return c.ActivityID
}

func (c *CreateEntityRequest) GetFillActivity() *bool {
	if c == nil {
		return nil
	}
	return c.FillActivity
}

func (c *CreateEntityRequest) GetAsync() *bool {
	if c == nil {
		return nil
	}
	return c.Async
}

func (c *CreateEntityRequest) GetValidate() *bool {
	if c == nil {
		return nil
	}
	return c.Validate
}

func (c *CreateEntityRequest) GetEntity() *shared.EntityInput {
	if c == nil {
		return nil
	}
	return c.Entity
}

type CreateEntityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	EntityItem *shared.EntityItem
	// Entity validation error when `?validate=true`
	EntityValidationV2ResultError *shared.EntityValidationV2ResultError
	// Too many requests
	TooManyRequestsError *shared.TooManyRequestsError
	Headers              map[string][]string
}

func (c *CreateEntityResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateEntityResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateEntityResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateEntityResponse) GetEntityItem() *shared.EntityItem {
	if c == nil {
		return nil
	}
	return c.EntityItem
}

func (c *CreateEntityResponse) GetEntityValidationV2ResultError() *shared.EntityValidationV2ResultError {
	if c == nil {
		return nil
	}
	return c.EntityValidationV2ResultError
}

func (c *CreateEntityResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if c == nil {
		return nil
	}
	return c.TooManyRequestsError
}

func (c *CreateEntityResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
