// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteTaxonomyClassificationRequest struct {
	// Taxonomy slug
	TaxonomySlug string `pathParam:"style=simple,explode=false,name=taxonomySlug"`
	// Taxonomy Classification slug
	ClassificationSlug string `pathParam:"style=simple,explode=false,name=classificationSlug"`
	// If true, the classification will be permanently deleted
	Permanent *bool `queryParam:"style=form,explode=true,name=permanent"`
}

func (o *DeleteTaxonomyClassificationRequest) GetTaxonomySlug() string {
	if o == nil {
		return ""
	}
	return o.TaxonomySlug
}

func (o *DeleteTaxonomyClassificationRequest) GetClassificationSlug() string {
	if o == nil {
		return ""
	}
	return o.ClassificationSlug
}

func (o *DeleteTaxonomyClassificationRequest) GetPermanent() *bool {
	if o == nil {
		return nil
	}
	return o.Permanent
}

type DeleteTaxonomyClassificationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteTaxonomyClassificationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteTaxonomyClassificationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteTaxonomyClassificationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
