// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type GetActivityRequest struct {
	// Activity Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Maximum number of operations to include in response (default: 10)
	//
	OperationsSize *int64 `default:"25" queryParam:"style=form,explode=true,name=operations_size"`
	// Pagination offset for operations
	//
	OperationsFrom *int64 `default:"0" queryParam:"style=form,explode=true,name=operations_from"`
}

func (g GetActivityRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetActivityRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetActivityRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetActivityRequest) GetOperationsSize() *int64 {
	if g == nil {
		return nil
	}
	return g.OperationsSize
}

func (g *GetActivityRequest) GetOperationsFrom() *int64 {
	if g == nil {
		return nil
	}
	return g.OperationsFrom
}

type GetActivityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ActivityItem *shared.ActivityItem
	// The requested resource was not found
	NotFoundError *shared.NotFoundError
}

func (g *GetActivityResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetActivityResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetActivityResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetActivityResponse) GetActivityItem() *shared.ActivityItem {
	if g == nil {
		return nil
	}
	return g.ActivityItem
}

func (g *GetActivityResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
