// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type GetSavedViewRequest struct {
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSavedViewRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetSavedViewResponseBody - A saved entity view
type GetSavedViewResponseBody struct {
	// Generated uuid for a saved view
	ID        *string `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (g *GetSavedViewResponseBody) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetSavedViewResponseBody) GetCreatedAt() *string {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *GetSavedViewResponseBody) GetUpdatedAt() *string {
	if g == nil {
		return nil
	}
	return g.UpdatedAt
}

type GetSavedViewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *GetSavedViewResponseBody
	// The requested resource was not found
	NotFoundError *shared.NotFoundError
}

func (g *GetSavedViewResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSavedViewResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSavedViewResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSavedViewResponse) GetObject() *GetSavedViewResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetSavedViewResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
