// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type GetSchemaExampleRequest struct {
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (g *GetSchemaExampleRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

// GetSchemaExampleResponseBody - Success
type GetSchemaExampleResponseBody struct {
}

type GetSchemaExampleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *GetSchemaExampleResponseBody
	// Too many requests
	TooManyRequestsError *shared.TooManyRequestsError
	Headers              map[string][]string
}

func (g *GetSchemaExampleResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSchemaExampleResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSchemaExampleResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSchemaExampleResponse) GetObject() *GetSchemaExampleResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetSchemaExampleResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if g == nil {
		return nil
	}
	return g.TooManyRequestsError
}

func (g *GetSchemaExampleResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
