// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type GetSchemaGroupHeadlineRequest struct {
	// Schema Slug and the Schema Group ID
	CompositeID string `pathParam:"style=simple,explode=false,name=composite_id"`
}

func (g *GetSchemaGroupHeadlineRequest) GetCompositeID() string {
	if g == nil {
		return ""
	}
	return g.CompositeID
}

type GetSchemaGroupHeadlineResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	GroupHeadlineWithCompositeID *shared.GroupHeadlineWithCompositeID
	// The requested resource was not found
	NotFoundError *shared.NotFoundError
}

func (g *GetSchemaGroupHeadlineResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSchemaGroupHeadlineResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSchemaGroupHeadlineResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSchemaGroupHeadlineResponse) GetGroupHeadlineWithCompositeID() *shared.GroupHeadlineWithCompositeID {
	if g == nil {
		return nil
	}
	return g.GroupHeadlineWithCompositeID
}

func (g *GetSchemaGroupHeadlineResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
