// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type GetSchemaRequest struct {
	// Entity Type
	Slug string  `pathParam:"style=simple,explode=false,name=slug"`
	ID   *string `queryParam:"style=form,explode=true,name=id"`
	// When true, return the latest version instead of the frozen version for frozen schemas.
	Latest *bool `default:"false" queryParam:"style=form,explode=true,name=latest"`
}

func (g GetSchemaRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSchemaRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSchemaRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

func (g *GetSchemaRequest) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetSchemaRequest) GetLatest() *bool {
	if g == nil {
		return nil
	}
	return g.Latest
}

type GetSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	EntitySchemaItem *shared.EntitySchemaItem
	// The requested resource was not found
	NotFoundError *shared.NotFoundError
}

func (g *GetSchemaResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSchemaResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSchemaResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSchemaResponse) GetEntitySchemaItem() *shared.EntitySchemaItem {
	if g == nil {
		return nil
	}
	return g.EntitySchemaItem
}

func (g *GetSchemaResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}
