// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type ImportEntitiesRequest struct {
	// The ID of the import job. This ID is used to track the progress and fetch the result of the import operation.
	JobID              *string                    `queryParam:"style=form,explode=true,name=job_id"`
	EntityImportParams *shared.EntityImportParams `request:"mediaType=application/json"`
}

func (i *ImportEntitiesRequest) GetJobID() *string {
	if i == nil {
		return nil
	}
	return i.JobID
}

func (i *ImportEntitiesRequest) GetEntityImportParams() *shared.EntityImportParams {
	if i == nil {
		return nil
	}
	return i.EntityImportParams
}

type ImportEntitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Too many requests
	TooManyRequestsError *shared.TooManyRequestsError
	Headers              map[string][]string
}

func (i *ImportEntitiesResponse) GetContentType() string {
	if i == nil {
		return ""
	}
	return i.ContentType
}

func (i *ImportEntitiesResponse) GetStatusCode() int {
	if i == nil {
		return 0
	}
	return i.StatusCode
}

func (i *ImportEntitiesResponse) GetRawResponse() *http.Response {
	if i == nil {
		return nil
	}
	return i.RawResponse
}

func (i *ImportEntitiesResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if i == nil {
		return nil
	}
	return i.TooManyRequestsError
}

func (i *ImportEntitiesResponse) GetHeaders() map[string][]string {
	if i == nil {
		return map[string][]string{}
	}
	return i.Headers
}
