// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type ListSavedViewsRequest struct {
	// Return views belonging to this schema
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
	// The sort key to use if present
	Sort *string `default:"name:asc" queryParam:"style=form,explode=true,name=sort"`
	From *int64  `default:"0" queryParam:"style=form,explode=true,name=from"`
	// Number of saved views to return
	Size   *int64   `default:"80" queryParam:"style=form,explode=true,name=size"`
	Fields []string `queryParam:"style=form,explode=true,name=fields"`
}

func (l ListSavedViewsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSavedViewsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSavedViewsRequest) GetSlug() *string {
	if l == nil {
		return nil
	}
	return l.Slug
}

func (l *ListSavedViewsRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListSavedViewsRequest) GetFrom() *int64 {
	if l == nil {
		return nil
	}
	return l.From
}

func (l *ListSavedViewsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

func (l *ListSavedViewsRequest) GetFields() []string {
	if l == nil {
		return nil
	}
	return l.Fields
}

type ListSavedViewsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	ListSavedViewsResults *shared.ListSavedViewsResults
}

func (l *ListSavedViewsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListSavedViewsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListSavedViewsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListSavedViewsResponse) GetListSavedViewsResults() *shared.ListSavedViewsResults {
	if l == nil {
		return nil
	}
	return l.ListSavedViewsResults
}
