// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/models/shared"
	"net/http"
)

type PutSchemaCapabilityRequest struct {
	// Schema Slug and the Attribute ID
	CompositeID                     string                                       `pathParam:"style=simple,explode=false,name=composite_id"`
	EntityCapabilityWithCompositeID *shared.EntityCapabilityWithCompositeIDInput `request:"mediaType=application/json"`
}

func (o *PutSchemaCapabilityRequest) GetCompositeID() string {
	if o == nil {
		return ""
	}
	return o.CompositeID
}

func (o *PutSchemaCapabilityRequest) GetEntityCapabilityWithCompositeID() *shared.EntityCapabilityWithCompositeIDInput {
	if o == nil {
		return nil
	}
	return o.EntityCapabilityWithCompositeID
}

type PutSchemaCapabilityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	EntityCapabilityWithCompositeID *shared.EntityCapabilityWithCompositeID
}

func (o *PutSchemaCapabilityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutSchemaCapabilityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutSchemaCapabilityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PutSchemaCapabilityResponse) GetEntityCapabilityWithCompositeID() *shared.EntityCapabilityWithCompositeID {
	if o == nil {
		return nil
	}
	return o.EntityCapabilityWithCompositeID
}
