// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type PutSchemaCapabilityRequest struct {
	// Schema Slug and the Attribute ID
	CompositeID                     string                                       `pathParam:"style=simple,explode=false,name=composite_id"`
	EntityCapabilityWithCompositeID *shared.EntityCapabilityWithCompositeIDInput `request:"mediaType=application/json"`
}

func (p *PutSchemaCapabilityRequest) GetCompositeID() string {
	if p == nil {
		return ""
	}
	return p.CompositeID
}

func (p *PutSchemaCapabilityRequest) GetEntityCapabilityWithCompositeID() *shared.EntityCapabilityWithCompositeIDInput {
	if p == nil {
		return nil
	}
	return p.EntityCapabilityWithCompositeID
}

type PutSchemaCapabilityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	EntityCapabilityWithCompositeID *shared.EntityCapabilityWithCompositeID
}

func (p *PutSchemaCapabilityResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutSchemaCapabilityResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutSchemaCapabilityResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutSchemaCapabilityResponse) GetEntityCapabilityWithCompositeID() *shared.EntityCapabilityWithCompositeID {
	if p == nil {
		return nil
	}
	return p.EntityCapabilityWithCompositeID
}
