// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type TaxonomyAutocompleteRequest struct {
	// Taxonomy slug
	TaxonomySlug string `pathParam:"style=simple,explode=false,name=taxonomySlug"`
	// Input to autocomplete
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Minimum number of results to return
	Size *float64 `queryParam:"style=form,explode=true,name=size"`
}

func (t *TaxonomyAutocompleteRequest) GetTaxonomySlug() string {
	if t == nil {
		return ""
	}
	return t.TaxonomySlug
}

func (t *TaxonomyAutocompleteRequest) GetQuery() *string {
	if t == nil {
		return nil
	}
	return t.Query
}

func (t *TaxonomyAutocompleteRequest) GetSize() *float64 {
	if t == nil {
		return nil
	}
	return t.Size
}

// TaxonomyAutocompleteResponseBody - Taxonomy classifications
type TaxonomyAutocompleteResponseBody struct {
	Results []shared.TaxonomyClassification `json:"results,omitempty"`
}

func (t *TaxonomyAutocompleteResponseBody) GetResults() []shared.TaxonomyClassification {
	if t == nil {
		return nil
	}
	return t.Results
}

type TaxonomyAutocompleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Taxonomy classifications
	Object *TaxonomyAutocompleteResponseBody
}

func (t *TaxonomyAutocompleteResponse) GetContentType() string {
	if t == nil {
		return ""
	}
	return t.ContentType
}

func (t *TaxonomyAutocompleteResponse) GetStatusCode() int {
	if t == nil {
		return 0
	}
	return t.StatusCode
}

func (t *TaxonomyAutocompleteResponse) GetRawResponse() *http.Response {
	if t == nil {
		return nil
	}
	return t.RawResponse
}

func (t *TaxonomyAutocompleteResponse) GetObject() *TaxonomyAutocompleteResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
