// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type UnfreezeSchemaRequest struct {
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (u *UnfreezeSchemaRequest) GetSlug() string {
	if u == nil {
		return ""
	}
	return u.Slug
}

type UnfreezeSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Schema unfrozen successfully
	EntitySchemaItem *shared.EntitySchemaItem
	// The requested resource was not found
	NotFoundError *shared.NotFoundError
}

func (u *UnfreezeSchemaResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UnfreezeSchemaResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UnfreezeSchemaResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UnfreezeSchemaResponse) GetEntitySchemaItem() *shared.EntitySchemaItem {
	if u == nil {
		return nil
	}
	return u.EntitySchemaItem
}

func (u *UnfreezeSchemaResponse) GetNotFoundError() *shared.NotFoundError {
	if u == nil {
		return nil
	}
	return u.NotFoundError
}
