// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"net/http"
)

type ValidateEntityRequest struct {
	// Entity Type
	Slug   string              `pathParam:"style=simple,explode=false,name=slug"`
	Entity *shared.EntityInput `request:"mediaType=application/json"`
}

func (v *ValidateEntityRequest) GetSlug() string {
	if v == nil {
		return ""
	}
	return v.Slug
}

func (v *ValidateEntityRequest) GetEntity() *shared.EntityInput {
	if v == nil {
		return nil
	}
	return v.Entity
}

type ValidateEntityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	EntityValidationResultSuccess *shared.EntityValidationResultSuccess
	// Error
	EntityValidationResultError *shared.EntityValidationResultError
	// Too many requests
	TooManyRequestsError *shared.TooManyRequestsError
	Headers              map[string][]string
}

func (v *ValidateEntityResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *ValidateEntityResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *ValidateEntityResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *ValidateEntityResponse) GetEntityValidationResultSuccess() *shared.EntityValidationResultSuccess {
	if v == nil {
		return nil
	}
	return v.EntityValidationResultSuccess
}

func (v *ValidateEntityResponse) GetEntityValidationResultError() *shared.EntityValidationResultError {
	if v == nil {
		return nil
	}
	return v.EntityValidationResultError
}

func (v *ValidateEntityResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if v == nil {
		return nil
	}
	return v.TooManyRequestsError
}

func (v *ValidateEntityResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
