// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

type Token struct {
	Sub             *string `json:"sub,omitempty"`
	Email           *string `json:"email,omitempty"`
	CognitoUsername *string `json:"cognito:username,omitempty"`
	CustomIvyUserID *string `json:"custom:ivy_user_id,omitempty"`
}

func (o *Token) GetSub() *string {
	if o == nil {
		return nil
	}
	return o.Sub
}

func (o *Token) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Token) GetCognitoUsername() *string {
	if o == nil {
		return nil
	}
	return o.CognitoUsername
}

func (o *Token) GetCustomIvyUserID() *string {
	if o == nil {
		return nil
	}
	return o.CustomIvyUserID
}

type EpilotAuth struct {
	Token *Token `json:"token,omitempty"`
}

func (o *EpilotAuth) GetToken() *Token {
	if o == nil {
		return nil
	}
	return o.Token
}

type ActivityCallerContext struct {
	EpilotAuth           *EpilotAuth `json:"EpilotAuth,omitempty"`
	AdditionalProperties any         `additionalProperties:"true" json:"-"`
}

func (a ActivityCallerContext) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivityCallerContext) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ActivityCallerContext) GetEpilotAuth() *EpilotAuth {
	if o == nil {
		return nil
	}
	return o.EpilotAuth
}

func (o *ActivityCallerContext) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
