// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// BadRequestError - A generic error returned by the API
type BadRequestError struct {
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
	// The error message
	Error *string `json:"error,omitempty"`
}

func (b *BadRequestError) GetStatus() *int64 {
	if b == nil {
		return nil
	}
	return b.Status
}

func (b *BadRequestError) GetError() *string {
	if b == nil {
		return nil
	}
	return b.Error
}
