// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ClassificationsUpdate struct {
	Create []TaxonomyClassificationInput `json:"create,omitempty"`
	Update []TaxonomyClassificationInput `json:"update,omitempty"`
	Delete []string                      `json:"delete,omitempty"`
}

func (c *ClassificationsUpdate) GetCreate() []TaxonomyClassificationInput {
	if c == nil {
		return nil
	}
	return c.Create
}

func (c *ClassificationsUpdate) GetUpdate() []TaxonomyClassificationInput {
	if c == nil {
		return nil
	}
	return c.Update
}

func (c *ClassificationsUpdate) GetDelete() []string {
	if c == nil {
		return nil
	}
	return c.Delete
}
