// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

type ViewType string

const (
	ViewTypeDefault ViewType = "default"
)

func (e ViewType) ToPointer() *ViewType {
	return &e
}
func (e *ViewType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "default":
		*e = ViewType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ViewType: %v", v)
	}
}

type RowActionsType string

const (
	RowActionsTypeStr          RowActionsType = "str"
	RowActionsTypeEntityAction RowActionsType = "EntityAction"
)

type RowActions struct {
	Str          *string
	EntityAction *EntityAction

	Type RowActionsType
}

func CreateRowActionsStr(str string) RowActions {
	typ := RowActionsTypeStr

	return RowActions{
		Str:  &str,
		Type: typ,
	}
}

func CreateRowActionsEntityAction(entityAction EntityAction) RowActions {
	typ := RowActionsTypeEntityAction

	return RowActions{
		EntityAction: &entityAction,
		Type:         typ,
	}
}

func (u *RowActions) UnmarshalJSON(data []byte) error {

	var entityAction EntityAction = EntityAction{}
	if err := utils.UnmarshalJSON(data, &entityAction, "", true, false); err == nil {
		u.EntityAction = &entityAction
		u.Type = RowActionsTypeEntityAction
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = RowActionsTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RowActions", string(data))
}

func (u RowActions) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.EntityAction != nil {
		return utils.MarshalJSON(u.EntityAction, "", true)
	}

	return nil, errors.New("could not marshal union type RowActions: all fields are null")
}

type BulkActionsType string

const (
	BulkActionsTypeStr          BulkActionsType = "str"
	BulkActionsTypeEntityAction BulkActionsType = "EntityAction"
)

type BulkActions struct {
	Str          *string
	EntityAction *EntityAction

	Type BulkActionsType
}

func CreateBulkActionsStr(str string) BulkActions {
	typ := BulkActionsTypeStr

	return BulkActions{
		Str:  &str,
		Type: typ,
	}
}

func CreateBulkActionsEntityAction(entityAction EntityAction) BulkActions {
	typ := BulkActionsTypeEntityAction

	return BulkActions{
		EntityAction: &entityAction,
		Type:         typ,
	}
}

func (u *BulkActions) UnmarshalJSON(data []byte) error {

	var entityAction EntityAction = EntityAction{}
	if err := utils.UnmarshalJSON(data, &entityAction, "", true, false); err == nil {
		u.EntityAction = &entityAction
		u.Type = BulkActionsTypeEntityAction
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, false); err == nil {
		u.Str = &str
		u.Type = BulkActionsTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BulkActions", string(data))
}

func (u BulkActions) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.EntityAction != nil {
		return utils.MarshalJSON(u.EntityAction, "", true)
	}

	return nil, errors.New("could not marshal union type BulkActions: all fields are null")
}

type Params struct {
}

type Options struct {
	Label  string  `json:"label"`
	Params *Params `json:"params,omitempty"`
}

func (o *Options) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *Options) GetParams() *Params {
	if o == nil {
		return nil
	}
	return o.Params
}

type NavbarActions struct {
	Type    string    `json:"type"`
	Options []Options `json:"options,omitempty"`
}

func (o *NavbarActions) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *NavbarActions) GetOptions() []Options {
	if o == nil {
		return nil
	}
	return o.Options
}

type EntityDefaultTable struct {
	ViewType      *ViewType       `json:"view_type,omitempty"`
	RowActions    []RowActions    `json:"row_actions,omitempty"`
	BulkActions   []BulkActions   `json:"bulk_actions,omitempty"`
	NavbarActions []NavbarActions `json:"navbar_actions,omitempty"`
	// Enable the thumbnail column
	EnableThumbnails *bool `default:"false" json:"enable_thumbnails"`
}

func (e EntityDefaultTable) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityDefaultTable) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *EntityDefaultTable) GetViewType() *ViewType {
	if o == nil {
		return nil
	}
	return o.ViewType
}

func (o *EntityDefaultTable) GetRowActions() []RowActions {
	if o == nil {
		return nil
	}
	return o.RowActions
}

func (o *EntityDefaultTable) GetBulkActions() []BulkActions {
	if o == nil {
		return nil
	}
	return o.BulkActions
}

func (o *EntityDefaultTable) GetNavbarActions() []NavbarActions {
	if o == nil {
		return nil
	}
	return o.NavbarActions
}

func (o *EntityDefaultTable) GetEnableThumbnails() *bool {
	if o == nil {
		return nil
	}
	return o.EnableThumbnails
}
