// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
	"time"
)

// EntityACL - Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
type EntityACL struct {
	View                 []string `json:"view,omitempty"`
	Edit                 []string `json:"edit,omitempty"`
	Delete               []string `json:"delete,omitempty"`
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
}

func (e EntityACL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityACL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityACL) GetView() []string {
	if e == nil {
		return nil
	}
	return e.View
}

func (e *EntityACL) GetEdit() []string {
	if e == nil {
		return nil
	}
	return e.Edit
}

func (e *EntityACL) GetDelete() []string {
	if e == nil {
		return nil
	}
	return e.Delete
}

func (e *EntityACL) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

type Entity struct {
	ID *string `json:"_id,omitempty"`
	// Organization Id the entity belongs to
	Org    *string       `json:"_org,omitempty"`
	Owners []EntityOwner `json:"_owners,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema *string `json:"_schema,omitempty"`
	// Title of entity
	Title     *string    `json:"_title,omitempty"`
	Tags      []string   `json:"_tags,omitempty"`
	CreatedAt *time.Time `json:"_created_at,omitempty"`
	UpdatedAt *time.Time `json:"_updated_at,omitempty"`
	DeletedAt *time.Time `json:"_deleted_at,omitempty"`
	ACL       *EntityACL `json:"_acl,omitempty"`
	Purpose   []string   `json:"_purpose,omitempty"`
	// Automatically computed purpose names from _purpose attribute
	PurposeName []string `json:"_purpose_name,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest             []string `json:"_manifest,omitempty"`
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
}

func (e Entity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Entity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Entity) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *Entity) GetOrg() *string {
	if e == nil {
		return nil
	}
	return e.Org
}

func (e *Entity) GetOwners() []EntityOwner {
	if e == nil {
		return nil
	}
	return e.Owners
}

func (e *Entity) GetSchema() *string {
	if e == nil {
		return nil
	}
	return e.Schema
}

func (e *Entity) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *Entity) GetTags() []string {
	if e == nil {
		return nil
	}
	return e.Tags
}

func (e *Entity) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *Entity) GetUpdatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}

func (e *Entity) GetDeletedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.DeletedAt
}

func (e *Entity) GetACL() *EntityACL {
	if e == nil {
		return nil
	}
	return e.ACL
}

func (e *Entity) GetPurpose() []string {
	if e == nil {
		return nil
	}
	return e.Purpose
}

func (e *Entity) GetPurposeName() []string {
	if e == nil {
		return nil
	}
	return e.PurposeName
}

func (e *Entity) GetManifest() []string {
	if e == nil {
		return nil
	}
	return e.Manifest
}

func (e *Entity) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

type EntityInput struct {
	ID *string `json:"_id,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema *string `json:"_schema,omitempty"`
	// Title of entity
	Title   *string    `json:"_title,omitempty"`
	Tags    []string   `json:"_tags,omitempty"`
	ACL     *EntityACL `json:"_acl,omitempty"`
	Purpose []string   `json:"_purpose,omitempty"`
	// Automatically computed purpose names from _purpose attribute
	PurposeName []string `json:"_purpose_name,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest             []string `json:"_manifest,omitempty"`
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
}

func (e EntityInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityInput) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EntityInput) GetSchema() *string {
	if e == nil {
		return nil
	}
	return e.Schema
}

func (e *EntityInput) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *EntityInput) GetTags() []string {
	if e == nil {
		return nil
	}
	return e.Tags
}

func (e *EntityInput) GetACL() *EntityACL {
	if e == nil {
		return nil
	}
	return e.ACL
}

func (e *EntityInput) GetPurpose() []string {
	if e == nil {
		return nil
	}
	return e.Purpose
}

func (e *EntityInput) GetPurposeName() []string {
	if e == nil {
		return nil
	}
	return e.PurposeName
}

func (e *EntityInput) GetManifest() []string {
	if e == nil {
		return nil
	}
	return e.Manifest
}

func (e *EntityInput) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}
