// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

// EntityAction - An entity action configured from the entity schema
type EntityAction struct {
	// A unique action name
	Action string  `json:"action"`
	Label  string  `json:"label"`
	Icon   *string `json:"icon,omitempty"`
	// Permission required to show the action.
	// If not provided, the action will be shown to all users.
	//
	Permission *string `json:"permission,omitempty"`
}

func (e EntityAction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityAction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"action", "label"}); err != nil {
		return err
	}
	return nil
}

func (e *EntityAction) GetAction() string {
	if e == nil {
		return ""
	}
	return e.Action
}

func (e *EntityAction) GetLabel() string {
	if e == nil {
		return ""
	}
	return e.Label
}

func (e *EntityAction) GetIcon() *string {
	if e == nil {
		return nil
	}
	return e.Icon
}

func (e *EntityAction) GetPermission() *string {
	if e == nil {
		return nil
	}
	return e.Permission
}
