// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
	"time"
)

type Operation string

const (
	OperationCreateEntity         Operation = "createEntity"
	OperationUpdateEntity         Operation = "updateEntity"
	OperationDeleteEntity         Operation = "deleteEntity"
	OperationSoftDeleteEntity     Operation = "softDeleteEntity"
	OperationRestoreEntity        Operation = "restoreEntity"
	OperationRelationsAdded       Operation = "relationsAdded"
	OperationRelationsRemoved     Operation = "relationsRemoved"
	OperationRelationsSoftDeleted Operation = "relationsSoftDeleted"
	OperationRelationsRestored    Operation = "relationsRestored"
	OperationRelationsDeleted     Operation = "relationsDeleted"
)

func (e Operation) ToPointer() *Operation {
	return &e
}
func (e *Operation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "createEntity":
		fallthrough
	case "updateEntity":
		fallthrough
	case "deleteEntity":
		fallthrough
	case "softDeleteEntity":
		fallthrough
	case "restoreEntity":
		fallthrough
	case "relationsAdded":
		fallthrough
	case "relationsRemoved":
		fallthrough
	case "relationsSoftDeleted":
		fallthrough
	case "relationsRestored":
		fallthrough
	case "relationsDeleted":
		*e = Operation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Operation: %v", v)
	}
}

type EntityOperationParams struct {
	ID *string `json:"id,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *string `json:"slug,omitempty"`
}

func (e *EntityOperationParams) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EntityOperationParams) GetSlug() *string {
	if e == nil {
		return nil
	}
	return e.Slug
}

// EntityOperationACL - Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
type EntityOperationACL struct {
	View                 []string `json:"view,omitempty"`
	Edit                 []string `json:"edit,omitempty"`
	Delete               []string `json:"delete,omitempty"`
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
}

func (e EntityOperationACL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityOperationACL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityOperationACL) GetView() []string {
	if e == nil {
		return nil
	}
	return e.View
}

func (e *EntityOperationACL) GetEdit() []string {
	if e == nil {
		return nil
	}
	return e.Edit
}

func (e *EntityOperationACL) GetDelete() []string {
	if e == nil {
		return nil
	}
	return e.Delete
}

func (e *EntityOperationACL) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

type Payload struct {
	ID *string `json:"_id,omitempty"`
	// Organization Id the entity belongs to
	Org    *string       `json:"_org,omitempty"`
	Owners []EntityOwner `json:"_owners,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema *string `json:"_schema,omitempty"`
	// Title of entity
	Title     *string             `json:"_title,omitempty"`
	Tags      []string            `json:"_tags,omitempty"`
	CreatedAt *time.Time          `json:"_created_at,omitempty"`
	UpdatedAt *time.Time          `json:"_updated_at,omitempty"`
	DeletedAt *time.Time          `json:"_deleted_at,omitempty"`
	ACL       *EntityOperationACL `json:"_acl,omitempty"`
	Purpose   []string            `json:"_purpose,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest             []string `json:"_manifest,omitempty"`
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
}

func (p Payload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Payload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Payload) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Payload) GetOrg() *string {
	if p == nil {
		return nil
	}
	return p.Org
}

func (p *Payload) GetOwners() []EntityOwner {
	if p == nil {
		return nil
	}
	return p.Owners
}

func (p *Payload) GetSchema() *string {
	if p == nil {
		return nil
	}
	return p.Schema
}

func (p *Payload) GetTitle() *string {
	if p == nil {
		return nil
	}
	return p.Title
}

func (p *Payload) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *Payload) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *Payload) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *Payload) GetDeletedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.DeletedAt
}

func (p *Payload) GetACL() *EntityOperationACL {
	if p == nil {
		return nil
	}
	return p.ACL
}

func (p *Payload) GetPurpose() []string {
	if p == nil {
		return nil
	}
	return p.Purpose
}

func (p *Payload) GetManifest() []string {
	if p == nil {
		return nil
	}
	return p.Manifest
}

func (p *Payload) GetAdditionalProperties() any {
	if p == nil {
		return nil
	}
	return p.AdditionalProperties
}

type Diff struct {
	Added   *Entity `json:"added,omitempty"`
	Updated *Entity `json:"updated,omitempty"`
	Deleted *Entity `json:"deleted,omitempty"`
}

func (d *Diff) GetAdded() *Entity {
	if d == nil {
		return nil
	}
	return d.Added
}

func (d *Diff) GetUpdated() *Entity {
	if d == nil {
		return nil
	}
	return d.Updated
}

func (d *Diff) GetDeleted() *Entity {
	if d == nil {
		return nil
	}
	return d.Deleted
}

type EntityOperation struct {
	Entity string `json:"entity"`
	Org    string `json:"org"`
	// See https://github.com/ulid/spec
	ActivityID *string                `json:"activity_id,omitempty"`
	Operation  Operation              `json:"operation"`
	Params     *EntityOperationParams `json:"params,omitempty"`
	Payload    *Payload               `json:"payload,omitempty"`
	Diff       *Diff                  `json:"diff,omitempty"`
}

func (e *EntityOperation) GetEntity() string {
	if e == nil {
		return ""
	}
	return e.Entity
}

func (e *EntityOperation) GetOrg() string {
	if e == nil {
		return ""
	}
	return e.Org
}

func (e *EntityOperation) GetActivityID() *string {
	if e == nil {
		return nil
	}
	return e.ActivityID
}

func (e *EntityOperation) GetOperation() Operation {
	if e == nil {
		return Operation("")
	}
	return e.Operation
}

func (e *EntityOperation) GetParams() *EntityOperationParams {
	if e == nil {
		return nil
	}
	return e.Params
}

func (e *EntityOperation) GetPayload() *Payload {
	if e == nil {
		return nil
	}
	return e.Payload
}

func (e *EntityOperation) GetDiff() *Diff {
	if e == nil {
		return nil
	}
	return e.Diff
}
