// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

// EntityACL - Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
type EntityACL struct {
	View                 []string    `json:"view,omitempty"`
	Edit                 []string    `json:"edit,omitempty"`
	Delete               []string    `json:"delete,omitempty"`
	AdditionalProperties interface{} `additionalProperties:"true" json:"-"`
}

func (e EntityACL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityACL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *EntityACL) GetView() []string {
	if o == nil {
		return nil
	}
	return o.View
}

func (o *EntityACL) GetEdit() []string {
	if o == nil {
		return nil
	}
	return o.Edit
}

func (o *EntityACL) GetDelete() []string {
	if o == nil {
		return nil
	}
	return o.Delete
}

func (o *EntityACL) GetAdditionalProperties() interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
