// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

type EntityNodesType string

const (
	EntityNodesTypeEntity        EntityNodesType = "Entity"
	EntityNodesTypeArrayOfEntity EntityNodesType = "arrayOfEntity"
)

type EntityNodes struct {
	Entity        *Entity  `queryParam:"inline"`
	ArrayOfEntity []Entity `queryParam:"inline"`

	Type EntityNodesType
}

func CreateEntityNodesEntity(entity Entity) EntityNodes {
	typ := EntityNodesTypeEntity

	return EntityNodes{
		Entity: &entity,
		Type:   typ,
	}
}

func CreateEntityNodesArrayOfEntity(arrayOfEntity []Entity) EntityNodes {
	typ := EntityNodesTypeArrayOfEntity

	return EntityNodes{
		ArrayOfEntity: arrayOfEntity,
		Type:          typ,
	}
}

func (u *EntityNodes) UnmarshalJSON(data []byte) error {

	var entity Entity = Entity{}
	if err := utils.UnmarshalJSON(data, &entity, "", true, false); err == nil {
		u.Entity = &entity
		u.Type = EntityNodesTypeEntity
		return nil
	}

	var arrayOfEntity []Entity = []Entity{}
	if err := utils.UnmarshalJSON(data, &arrayOfEntity, "", true, false); err == nil {
		u.ArrayOfEntity = arrayOfEntity
		u.Type = EntityNodesTypeArrayOfEntity
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EntityNodes", string(data))
}

func (u EntityNodes) MarshalJSON() ([]byte, error) {
	if u.Entity != nil {
		return utils.MarshalJSON(u.Entity, "", true)
	}

	if u.ArrayOfEntity != nil {
		return utils.MarshalJSON(u.ArrayOfEntity, "", true)
	}

	return nil, errors.New("could not marshal union type EntityNodes: all fields are null")
}

type GraphQueryResponse struct {
	// Map of node IDs to arrays of entity IDs found for that node (present when hydrate=false)
	Nodes map[string][]string `json:"nodes,omitempty"`
	// Map of node IDs to entity objects or arrays of entity objects (present when hydrate=true).
	// The seed node always returns a single Entity object.
	// Other nodes return a single Entity object if they contain exactly one entity, or an array of Entity objects if they contain multiple entities.
	//
	EntityNodes map[string]EntityNodes `json:"entityNodes,omitempty"`
	// List of edges as defined in the request
	Edges []GraphEdge `json:"edges"`
}

func (o *GraphQueryResponse) GetNodes() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Nodes
}

func (o *GraphQueryResponse) GetEntityNodes() map[string]EntityNodes {
	if o == nil {
		return nil
	}
	return o.EntityNodes
}

func (o *GraphQueryResponse) GetEdges() []GraphEdge {
	if o == nil {
		return []GraphEdge{}
	}
	return o.Edges
}
