// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

// MultiSelectAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type MultiSelectAttributeConstraints struct {
}

// MultiSelectAttributeInfoHelpers - A set of configurations meant to document and assist the user in filling the attribute.
type MultiSelectAttributeInfoHelpers struct {
	// The text to be displayed in the attribute hint helper.
	// When specified it overrides the `hint_text_key` configuration.
	//
	HintText *string `json:"hint_text,omitempty"`
	// The key of the hint text to be displayed in the attribute hint helper.
	// The key should be a valid i18n key.
	//
	HintTextKey *string `json:"hint_text_key,omitempty"`
	// The name of the custom component to be used as the hint helper.
	// The component should be registered in the `@epilot360/entity-ui` on the index of the components directory.
	// When specified it overrides the `hint_text` or `hint_text_key` configuration.
	//
	HintCustomComponent *string `json:"hint_custom_component,omitempty"`
	// The placement of the hint tooltip.
	// The value should be a valid `@mui/core` tooltip placement.
	//
	HintTooltipPlacement *string `json:"hint_tooltip_placement,omitempty"`
}

func (o *MultiSelectAttributeInfoHelpers) GetHintText() *string {
	if o == nil {
		return nil
	}
	return o.HintText
}

func (o *MultiSelectAttributeInfoHelpers) GetHintTextKey() *string {
	if o == nil {
		return nil
	}
	return o.HintTextKey
}

func (o *MultiSelectAttributeInfoHelpers) GetHintCustomComponent() *string {
	if o == nil {
		return nil
	}
	return o.HintCustomComponent
}

func (o *MultiSelectAttributeInfoHelpers) GetHintTooltipPlacement() *string {
	if o == nil {
		return nil
	}
	return o.HintTooltipPlacement
}

type MultiSelectAttributeType string

const (
	MultiSelectAttributeTypeMultiselect MultiSelectAttributeType = "multiselect"
	MultiSelectAttributeTypeCheckbox    MultiSelectAttributeType = "checkbox"
)

func (e MultiSelectAttributeType) ToPointer() *MultiSelectAttributeType {
	return &e
}

func (e *MultiSelectAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "multiselect":
		fallthrough
	case "checkbox":
		*e = MultiSelectAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MultiSelectAttributeType: %v", v)
	}
}

type Two struct {
	Value string  `json:"value"`
	Title *string `json:"title,omitempty"`
}

func (o *Two) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

func (o *Two) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

type MultiSelectAttributeOptionsType string

const (
	MultiSelectAttributeOptionsTypeStr MultiSelectAttributeOptionsType = "str"
	MultiSelectAttributeOptionsTypeTwo MultiSelectAttributeOptionsType = "2"
)

type MultiSelectAttributeOptions struct {
	Str *string
	Two *Two

	Type MultiSelectAttributeOptionsType
}

func CreateMultiSelectAttributeOptionsStr(str string) MultiSelectAttributeOptions {
	typ := MultiSelectAttributeOptionsTypeStr

	return MultiSelectAttributeOptions{
		Str:  &str,
		Type: typ,
	}
}

func CreateMultiSelectAttributeOptionsTwo(two Two) MultiSelectAttributeOptions {
	typ := MultiSelectAttributeOptionsTypeTwo

	return MultiSelectAttributeOptions{
		Two:  &two,
		Type: typ,
	}
}

func (u *MultiSelectAttributeOptions) UnmarshalJSON(data []byte) error {

	var two Two = Two{}
	if err := utils.UnmarshalJSON(data, &two, "", true, true); err == nil {
		u.Two = &two
		u.Type = MultiSelectAttributeOptionsTypeTwo
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = MultiSelectAttributeOptionsTypeStr
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u MultiSelectAttributeOptions) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// MultiSelectAttribute - Multi Choice Selection
type MultiSelectAttribute struct {
	Name        string  `json:"name"`
	Label       string  `json:"label"`
	Placeholder *string `json:"placeholder,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable *bool `json:"show_in_table,omitempty"`
	// Allow sorting by this attribute in table views if `show_in_table` is true
	Sortable     *bool       `default:"true" json:"sortable"`
	Required     *bool       `default:"false" json:"required"`
	Readonly     *bool       `default:"false" json:"readonly"`
	Deprecated   *bool       `default:"false" json:"deprecated"`
	DefaultValue interface{} `json:"default_value,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group *string `json:"group,omitempty"`
	// Attribute sort order (ascending) in group
	Order  *int64  `json:"order,omitempty"`
	Layout *string `json:"layout,omitempty"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon *string `json:"icon,omitempty"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string  `json:"render_condition,omitempty"`
	Purpose         []string `json:"_purpose,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints *MultiSelectAttributeConstraints `json:"constraints,omitempty"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// This attribute should only be active when all the settings have the correct value
	SettingsFlag          []SettingFlag `json:"settings_flag,omitempty"`
	ValueFormatter        *string       `json:"value_formatter,omitempty"`
	PreviewValueFormatter *string       `json:"preview_value_formatter,omitempty"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `default:"true" json:"protected"`
	// A set of configurations meant to document and assist the user in filling the attribute.
	InfoHelpers *MultiSelectAttributeInfoHelpers `json:"info_helpers,omitempty"`
	Type        *MultiSelectAttributeType        `json:"type,omitempty"`
	// controls if the matching of values against the options is case sensitive or not
	DisableCaseSensitive *bool `json:"disable_case_sensitive,omitempty"`
	// controls if the 360 ui will allow the user to enter a value which is not defined by the options
	AllowExtraOptions *bool                         `json:"allow_extra_options,omitempty"`
	Options           []MultiSelectAttributeOptions `json:"options,omitempty"`
	// Allow arbitrary input values in addition to provided options
	AllowAny *bool `json:"allow_any,omitempty"`
}

func (m MultiSelectAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MultiSelectAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *MultiSelectAttribute) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *MultiSelectAttribute) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *MultiSelectAttribute) GetPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.Placeholder
}

func (o *MultiSelectAttribute) GetHidden() *bool {
	if o == nil {
		return nil
	}
	return o.Hidden
}

func (o *MultiSelectAttribute) GetShowInTable() *bool {
	if o == nil {
		return nil
	}
	return o.ShowInTable
}

func (o *MultiSelectAttribute) GetSortable() *bool {
	if o == nil {
		return nil
	}
	return o.Sortable
}

func (o *MultiSelectAttribute) GetRequired() *bool {
	if o == nil {
		return nil
	}
	return o.Required
}

func (o *MultiSelectAttribute) GetReadonly() *bool {
	if o == nil {
		return nil
	}
	return o.Readonly
}

func (o *MultiSelectAttribute) GetDeprecated() *bool {
	if o == nil {
		return nil
	}
	return o.Deprecated
}

func (o *MultiSelectAttribute) GetDefaultValue() interface{} {
	if o == nil {
		return nil
	}
	return o.DefaultValue
}

func (o *MultiSelectAttribute) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *MultiSelectAttribute) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *MultiSelectAttribute) GetLayout() *string {
	if o == nil {
		return nil
	}
	return o.Layout
}

func (o *MultiSelectAttribute) GetHideLabel() *bool {
	if o == nil {
		return nil
	}
	return o.HideLabel
}

func (o *MultiSelectAttribute) GetIcon() *string {
	if o == nil {
		return nil
	}
	return o.Icon
}

func (o *MultiSelectAttribute) GetRenderCondition() *string {
	if o == nil {
		return nil
	}
	return o.RenderCondition
}

func (o *MultiSelectAttribute) GetPurpose() []string {
	if o == nil {
		return nil
	}
	return o.Purpose
}

func (o *MultiSelectAttribute) GetConstraints() *MultiSelectAttributeConstraints {
	if o == nil {
		return nil
	}
	return o.Constraints
}

func (o *MultiSelectAttribute) GetFeatureFlag() *string {
	if o == nil {
		return nil
	}
	return o.FeatureFlag
}

func (o *MultiSelectAttribute) GetSettingsFlag() []SettingFlag {
	if o == nil {
		return nil
	}
	return o.SettingsFlag
}

func (o *MultiSelectAttribute) GetValueFormatter() *string {
	if o == nil {
		return nil
	}
	return o.ValueFormatter
}

func (o *MultiSelectAttribute) GetPreviewValueFormatter() *string {
	if o == nil {
		return nil
	}
	return o.PreviewValueFormatter
}

func (o *MultiSelectAttribute) GetEntityBuilderDisableEdit() *bool {
	if o == nil {
		return nil
	}
	return o.EntityBuilderDisableEdit
}

func (o *MultiSelectAttribute) GetProtected() *bool {
	if o == nil {
		return nil
	}
	return o.Protected
}

func (o *MultiSelectAttribute) GetInfoHelpers() *MultiSelectAttributeInfoHelpers {
	if o == nil {
		return nil
	}
	return o.InfoHelpers
}

func (o *MultiSelectAttribute) GetType() *MultiSelectAttributeType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *MultiSelectAttribute) GetDisableCaseSensitive() *bool {
	if o == nil {
		return nil
	}
	return o.DisableCaseSensitive
}

func (o *MultiSelectAttribute) GetAllowExtraOptions() *bool {
	if o == nil {
		return nil
	}
	return o.AllowExtraOptions
}

func (o *MultiSelectAttribute) GetOptions() []MultiSelectAttributeOptions {
	if o == nil {
		return nil
	}
	return o.Options
}

func (o *MultiSelectAttribute) GetAllowAny() *bool {
	if o == nil {
		return nil
	}
	return o.AllowAny
}
