// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

// MultiSelectAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type MultiSelectAttributeConstraints struct {
}

func (m MultiSelectAttributeConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MultiSelectAttributeConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

// MultiSelectAttributeInfoHelpers - A set of configurations meant to document and assist the user in filling the attribute.
type MultiSelectAttributeInfoHelpers struct {
	// The text to be displayed in the attribute hint helper.
	// When specified it overrides the `hint_text_key` configuration.
	//
	HintText *string `json:"hint_text,omitempty"`
	// The key of the hint text to be displayed in the attribute hint helper.
	// The key should be a valid i18n key.
	//
	HintTextKey *string `json:"hint_text_key,omitempty"`
	// The name of the custom component to be used as the hint helper.
	// The component should be registered in the `@epilot360/entity-ui` on the index of the components directory.
	// When specified it overrides the `hint_text` or `hint_text_key` configuration.
	//
	HintCustomComponent *string `json:"hint_custom_component,omitempty"`
	// The placement of the hint tooltip.
	// The value should be a valid `@mui/core` tooltip placement.
	//
	HintTooltipPlacement *string `json:"hint_tooltip_placement,omitempty"`
}

func (m MultiSelectAttributeInfoHelpers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MultiSelectAttributeInfoHelpers) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MultiSelectAttributeInfoHelpers) GetHintText() *string {
	if m == nil {
		return nil
	}
	return m.HintText
}

func (m *MultiSelectAttributeInfoHelpers) GetHintTextKey() *string {
	if m == nil {
		return nil
	}
	return m.HintTextKey
}

func (m *MultiSelectAttributeInfoHelpers) GetHintCustomComponent() *string {
	if m == nil {
		return nil
	}
	return m.HintCustomComponent
}

func (m *MultiSelectAttributeInfoHelpers) GetHintTooltipPlacement() *string {
	if m == nil {
		return nil
	}
	return m.HintTooltipPlacement
}

type MultiSelectAttributeType string

const (
	MultiSelectAttributeTypeMultiselect MultiSelectAttributeType = "multiselect"
	MultiSelectAttributeTypeCheckbox    MultiSelectAttributeType = "checkbox"
)

func (e MultiSelectAttributeType) ToPointer() *MultiSelectAttributeType {
	return &e
}
func (e *MultiSelectAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "multiselect":
		fallthrough
	case "checkbox":
		*e = MultiSelectAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MultiSelectAttributeType: %v", v)
	}
}

type Two struct {
	Value string  `json:"value"`
	Title *string `json:"title,omitempty"`
}

func (t Two) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Two) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"value"}); err != nil {
		return err
	}
	return nil
}

func (t *Two) GetValue() string {
	if t == nil {
		return ""
	}
	return t.Value
}

func (t *Two) GetTitle() *string {
	if t == nil {
		return nil
	}
	return t.Title
}

type OptionsObjType string

const (
	OptionsObjTypeStr OptionsObjType = "str"
	OptionsObjTypeTwo OptionsObjType = "2"
)

type OptionsObj struct {
	Str *string `queryParam:"inline" name:"options"`
	Two *Two    `queryParam:"inline" name:"options"`

	Type OptionsObjType
}

func CreateOptionsObjStr(str string) OptionsObj {
	typ := OptionsObjTypeStr

	return OptionsObj{
		Str:  &str,
		Type: typ,
	}
}

func CreateOptionsObjTwo(two Two) OptionsObj {
	typ := OptionsObjTypeTwo

	return OptionsObj{
		Two:  &two,
		Type: typ,
	}
}

func (u *OptionsObj) UnmarshalJSON(data []byte) error {

	var two Two = Two{}
	if err := utils.UnmarshalJSON(data, &two, "", true, nil); err == nil {
		u.Two = &two
		u.Type = OptionsObjTypeTwo
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = OptionsObjTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for OptionsObj", string(data))
}

func (u OptionsObj) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	return nil, errors.New("could not marshal union type OptionsObj: all fields are null")
}

// MultiSelectAttribute - Multi Choice Selection
type MultiSelectAttribute struct {
	// ID for the entity attribute
	ID          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	Label       string  `json:"label"`
	Placeholder *string `json:"placeholder,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable *bool `json:"show_in_table,omitempty"`
	// Allow sorting by this attribute in table views if `show_in_table` is true
	Sortable     *bool `default:"true" json:"sortable"`
	Required     *bool `default:"false" json:"required"`
	Readonly     *bool `default:"false" json:"readonly"`
	Deprecated   *bool `default:"false" json:"deprecated"`
	DefaultValue any   `json:"default_value,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group *string `json:"group,omitempty"`
	// Attribute sort order (ascending) in group
	Order  *int64  `json:"order,omitempty"`
	Layout *string `json:"layout,omitempty"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon *string `json:"icon,omitempty"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string  `json:"render_condition,omitempty"`
	Purpose         []string `json:"_purpose,omitempty"`
	// Manifest ID used to create/update the schema attribute
	Manifest []string `json:"_manifest,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints *MultiSelectAttributeConstraints `json:"constraints,omitempty"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// This attribute should only be active when one of the provided settings have the correct value
	SettingsFlag          []SettingFlag `json:"settings_flag,omitempty"`
	ValueFormatter        *string       `json:"value_formatter,omitempty"`
	PreviewValueFormatter *string       `json:"preview_value_formatter,omitempty"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `json:"protected,omitempty"`
	// A set of configurations meant to document and assist the user in filling the attribute.
	InfoHelpers *MultiSelectAttributeInfoHelpers `json:"info_helpers,omitempty"`
	// The attribute is a repeatable
	Repeatable *bool                    `json:"repeatable,omitempty"`
	HasPrimary *bool                    `json:"has_primary,omitempty"`
	Type       MultiSelectAttributeType `json:"type"`
	// controls if the matching of values against the options is case sensitive or not
	DisableCaseSensitive *bool `json:"disable_case_sensitive,omitempty"`
	// controls if the 360 ui will allow the user to enter a value which is not defined by the options
	AllowExtraOptions *bool         `json:"allow_extra_options,omitempty"`
	Options           []*OptionsObj `json:"options,omitempty"`
	// Allow arbitrary input values in addition to provided options
	AllowAny *bool `json:"allow_any,omitempty"`
}

func (m MultiSelectAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MultiSelectAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"name", "label", "type"}); err != nil {
		return err
	}
	return nil
}

func (m *MultiSelectAttribute) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *MultiSelectAttribute) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MultiSelectAttribute) GetLabel() string {
	if m == nil {
		return ""
	}
	return m.Label
}

func (m *MultiSelectAttribute) GetPlaceholder() *string {
	if m == nil {
		return nil
	}
	return m.Placeholder
}

func (m *MultiSelectAttribute) GetHidden() *bool {
	if m == nil {
		return nil
	}
	return m.Hidden
}

func (m *MultiSelectAttribute) GetShowInTable() *bool {
	if m == nil {
		return nil
	}
	return m.ShowInTable
}

func (m *MultiSelectAttribute) GetSortable() *bool {
	if m == nil {
		return nil
	}
	return m.Sortable
}

func (m *MultiSelectAttribute) GetRequired() *bool {
	if m == nil {
		return nil
	}
	return m.Required
}

func (m *MultiSelectAttribute) GetReadonly() *bool {
	if m == nil {
		return nil
	}
	return m.Readonly
}

func (m *MultiSelectAttribute) GetDeprecated() *bool {
	if m == nil {
		return nil
	}
	return m.Deprecated
}

func (m *MultiSelectAttribute) GetDefaultValue() any {
	if m == nil {
		return nil
	}
	return m.DefaultValue
}

func (m *MultiSelectAttribute) GetGroup() *string {
	if m == nil {
		return nil
	}
	return m.Group
}

func (m *MultiSelectAttribute) GetOrder() *int64 {
	if m == nil {
		return nil
	}
	return m.Order
}

func (m *MultiSelectAttribute) GetLayout() *string {
	if m == nil {
		return nil
	}
	return m.Layout
}

func (m *MultiSelectAttribute) GetHideLabel() *bool {
	if m == nil {
		return nil
	}
	return m.HideLabel
}

func (m *MultiSelectAttribute) GetIcon() *string {
	if m == nil {
		return nil
	}
	return m.Icon
}

func (m *MultiSelectAttribute) GetRenderCondition() *string {
	if m == nil {
		return nil
	}
	return m.RenderCondition
}

func (m *MultiSelectAttribute) GetPurpose() []string {
	if m == nil {
		return nil
	}
	return m.Purpose
}

func (m *MultiSelectAttribute) GetManifest() []string {
	if m == nil {
		return nil
	}
	return m.Manifest
}

func (m *MultiSelectAttribute) GetConstraints() *MultiSelectAttributeConstraints {
	if m == nil {
		return nil
	}
	return m.Constraints
}

func (m *MultiSelectAttribute) GetFeatureFlag() *string {
	if m == nil {
		return nil
	}
	return m.FeatureFlag
}

func (m *MultiSelectAttribute) GetSettingsFlag() []SettingFlag {
	if m == nil {
		return nil
	}
	return m.SettingsFlag
}

func (m *MultiSelectAttribute) GetValueFormatter() *string {
	if m == nil {
		return nil
	}
	return m.ValueFormatter
}

func (m *MultiSelectAttribute) GetPreviewValueFormatter() *string {
	if m == nil {
		return nil
	}
	return m.PreviewValueFormatter
}

func (m *MultiSelectAttribute) GetEntityBuilderDisableEdit() *bool {
	if m == nil {
		return nil
	}
	return m.EntityBuilderDisableEdit
}

func (m *MultiSelectAttribute) GetProtected() *bool {
	if m == nil {
		return nil
	}
	return m.Protected
}

func (m *MultiSelectAttribute) GetInfoHelpers() *MultiSelectAttributeInfoHelpers {
	if m == nil {
		return nil
	}
	return m.InfoHelpers
}

func (m *MultiSelectAttribute) GetRepeatable() *bool {
	if m == nil {
		return nil
	}
	return m.Repeatable
}

func (m *MultiSelectAttribute) GetHasPrimary() *bool {
	if m == nil {
		return nil
	}
	return m.HasPrimary
}

func (m *MultiSelectAttribute) GetType() MultiSelectAttributeType {
	if m == nil {
		return MultiSelectAttributeType("")
	}
	return m.Type
}

func (m *MultiSelectAttribute) GetDisableCaseSensitive() *bool {
	if m == nil {
		return nil
	}
	return m.DisableCaseSensitive
}

func (m *MultiSelectAttribute) GetAllowExtraOptions() *bool {
	if m == nil {
		return nil
	}
	return m.AllowExtraOptions
}

func (m *MultiSelectAttribute) GetOptions() []*OptionsObj {
	if m == nil {
		return nil
	}
	return m.Options
}

func (m *MultiSelectAttribute) GetAllowAny() *bool {
	if m == nil {
		return nil
	}
	return m.AllowAny
}
