// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

// PurposeAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type PurposeAttributeConstraints struct {
}

func (p PurposeAttributeConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PurposeAttributeConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

// PurposeAttributeInfoHelpers - A set of configurations meant to document and assist the user in filling the attribute.
type PurposeAttributeInfoHelpers struct {
	// The text to be displayed in the attribute hint helper.
	// When specified it overrides the `hint_text_key` configuration.
	//
	HintText *string `json:"hint_text,omitempty"`
	// The key of the hint text to be displayed in the attribute hint helper.
	// The key should be a valid i18n key.
	//
	HintTextKey *string `json:"hint_text_key,omitempty"`
	// The name of the custom component to be used as the hint helper.
	// The component should be registered in the `@epilot360/entity-ui` on the index of the components directory.
	// When specified it overrides the `hint_text` or `hint_text_key` configuration.
	//
	HintCustomComponent *string `json:"hint_custom_component,omitempty"`
	// The placement of the hint tooltip.
	// The value should be a valid `@mui/core` tooltip placement.
	//
	HintTooltipPlacement *string `json:"hint_tooltip_placement,omitempty"`
}

func (p PurposeAttributeInfoHelpers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PurposeAttributeInfoHelpers) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PurposeAttributeInfoHelpers) GetHintText() *string {
	if p == nil {
		return nil
	}
	return p.HintText
}

func (p *PurposeAttributeInfoHelpers) GetHintTextKey() *string {
	if p == nil {
		return nil
	}
	return p.HintTextKey
}

func (p *PurposeAttributeInfoHelpers) GetHintCustomComponent() *string {
	if p == nil {
		return nil
	}
	return p.HintCustomComponent
}

func (p *PurposeAttributeInfoHelpers) GetHintTooltipPlacement() *string {
	if p == nil {
		return nil
	}
	return p.HintTooltipPlacement
}

type PurposeAttributeType string

const (
	PurposeAttributeTypePurpose PurposeAttributeType = "purpose"
)

func (e PurposeAttributeType) ToPointer() *PurposeAttributeType {
	return &e
}
func (e *PurposeAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "purpose":
		*e = PurposeAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PurposeAttributeType: %v", v)
	}
}

// PurposeAttribute - Entity Taxonomy
type PurposeAttribute struct {
	// ID for the entity attribute
	ID          *string `json:"id,omitempty"`
	Name        string  `json:"name"`
	Label       string  `json:"label"`
	Placeholder *string `json:"placeholder,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable *bool `json:"show_in_table,omitempty"`
	// Allow sorting by this attribute in table views if `show_in_table` is true
	Sortable     *bool `default:"true" json:"sortable"`
	Required     *bool `default:"false" json:"required"`
	Readonly     *bool `default:"false" json:"readonly"`
	Deprecated   *bool `default:"false" json:"deprecated"`
	DefaultValue any   `json:"default_value,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group *string `json:"group,omitempty"`
	// Attribute sort order (ascending) in group
	Order  *int64  `json:"order,omitempty"`
	Layout *string `json:"layout,omitempty"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon *string `json:"icon,omitempty"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string  `json:"render_condition,omitempty"`
	Purpose         []string `json:"_purpose,omitempty"`
	// Manifest ID used to create/update the schema attribute
	Manifest []string `json:"_manifest,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints *PurposeAttributeConstraints `json:"constraints,omitempty"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// This attribute should only be active when one of the provided settings have the correct value
	SettingsFlag          []SettingFlag `json:"settings_flag,omitempty"`
	ValueFormatter        *string       `json:"value_formatter,omitempty"`
	PreviewValueFormatter *string       `json:"preview_value_formatter,omitempty"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `json:"protected,omitempty"`
	// A set of configurations meant to document and assist the user in filling the attribute.
	InfoHelpers *PurposeAttributeInfoHelpers `json:"info_helpers,omitempty"`
	// The attribute is a repeatable
	Repeatable *bool                `json:"repeatable,omitempty"`
	HasPrimary *bool                `json:"has_primary,omitempty"`
	Type       PurposeAttributeType `json:"type"`
}

func (p PurposeAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PurposeAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"name", "label", "type"}); err != nil {
		return err
	}
	return nil
}

func (p *PurposeAttribute) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PurposeAttribute) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PurposeAttribute) GetLabel() string {
	if p == nil {
		return ""
	}
	return p.Label
}

func (p *PurposeAttribute) GetPlaceholder() *string {
	if p == nil {
		return nil
	}
	return p.Placeholder
}

func (p *PurposeAttribute) GetHidden() *bool {
	if p == nil {
		return nil
	}
	return p.Hidden
}

func (p *PurposeAttribute) GetShowInTable() *bool {
	if p == nil {
		return nil
	}
	return p.ShowInTable
}

func (p *PurposeAttribute) GetSortable() *bool {
	if p == nil {
		return nil
	}
	return p.Sortable
}

func (p *PurposeAttribute) GetRequired() *bool {
	if p == nil {
		return nil
	}
	return p.Required
}

func (p *PurposeAttribute) GetReadonly() *bool {
	if p == nil {
		return nil
	}
	return p.Readonly
}

func (p *PurposeAttribute) GetDeprecated() *bool {
	if p == nil {
		return nil
	}
	return p.Deprecated
}

func (p *PurposeAttribute) GetDefaultValue() any {
	if p == nil {
		return nil
	}
	return p.DefaultValue
}

func (p *PurposeAttribute) GetGroup() *string {
	if p == nil {
		return nil
	}
	return p.Group
}

func (p *PurposeAttribute) GetOrder() *int64 {
	if p == nil {
		return nil
	}
	return p.Order
}

func (p *PurposeAttribute) GetLayout() *string {
	if p == nil {
		return nil
	}
	return p.Layout
}

func (p *PurposeAttribute) GetHideLabel() *bool {
	if p == nil {
		return nil
	}
	return p.HideLabel
}

func (p *PurposeAttribute) GetIcon() *string {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *PurposeAttribute) GetRenderCondition() *string {
	if p == nil {
		return nil
	}
	return p.RenderCondition
}

func (p *PurposeAttribute) GetPurpose() []string {
	if p == nil {
		return nil
	}
	return p.Purpose
}

func (p *PurposeAttribute) GetManifest() []string {
	if p == nil {
		return nil
	}
	return p.Manifest
}

func (p *PurposeAttribute) GetConstraints() *PurposeAttributeConstraints {
	if p == nil {
		return nil
	}
	return p.Constraints
}

func (p *PurposeAttribute) GetFeatureFlag() *string {
	if p == nil {
		return nil
	}
	return p.FeatureFlag
}

func (p *PurposeAttribute) GetSettingsFlag() []SettingFlag {
	if p == nil {
		return nil
	}
	return p.SettingsFlag
}

func (p *PurposeAttribute) GetValueFormatter() *string {
	if p == nil {
		return nil
	}
	return p.ValueFormatter
}

func (p *PurposeAttribute) GetPreviewValueFormatter() *string {
	if p == nil {
		return nil
	}
	return p.PreviewValueFormatter
}

func (p *PurposeAttribute) GetEntityBuilderDisableEdit() *bool {
	if p == nil {
		return nil
	}
	return p.EntityBuilderDisableEdit
}

func (p *PurposeAttribute) GetProtected() *bool {
	if p == nil {
		return nil
	}
	return p.Protected
}

func (p *PurposeAttribute) GetInfoHelpers() *PurposeAttributeInfoHelpers {
	if p == nil {
		return nil
	}
	return p.InfoHelpers
}

func (p *PurposeAttribute) GetRepeatable() *bool {
	if p == nil {
		return nil
	}
	return p.Repeatable
}

func (p *PurposeAttribute) GetHasPrimary() *bool {
	if p == nil {
		return nil
	}
	return p.HasPrimary
}

func (p *PurposeAttribute) GetType() PurposeAttributeType {
	if p == nil {
		return PurposeAttributeType("")
	}
	return p.Type
}
