// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/internal/utils"
)

type RelationItem struct {
	EntityID string `json:"entity_id"`
	// Organization Id the entity belongs to
	OrgID     *string  `json:"org_id,omitempty"`
	Attribute string   `json:"attribute"`
	Tags      []string `json:"_tags,omitempty"`
	// Whether this is a reverse relation
	Reverse *bool `json:"reverse,omitempty"`
}

func (r RelationItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RelationItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"entity_id", "attribute"}); err != nil {
		return err
	}
	return nil
}

func (r *RelationItem) GetEntityID() string {
	if r == nil {
		return ""
	}
	return r.EntityID
}

func (r *RelationItem) GetOrgID() *string {
	if r == nil {
		return nil
	}
	return r.OrgID
}

func (r *RelationItem) GetAttribute() string {
	if r == nil {
		return ""
	}
	return r.Attribute
}

func (r *RelationItem) GetTags() []string {
	if r == nil {
		return nil
	}
	return r.Tags
}

func (r *RelationItem) GetReverse() *bool {
	if r == nil {
		return nil
	}
	return r.Reverse
}
