// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SettingFlag struct {
	// The name of the organization setting to check
	Name *string `json:"name,omitempty"`
	// Whether the setting should be enabled or not
	Enabled *bool `json:"enabled,omitempty"`
}

func (o *SettingFlag) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *SettingFlag) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}
