// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TaxonomyInput struct {
	// URL-friendly name for taxonomy
	Slug *string `json:"slug,omitempty"`
	// A human friendly name of a Taxonomy e.g. Purpose, Product Category, Folder, Tag
	Name *string `json:"name,omitempty"`
	// Plural name of a Taxonomy e.g. Purposes, Product Categories, Folders, Tags. Defaults to name is not provided.
	Plural *string `json:"plural,omitempty"`
	// Icon name for the taxonomy (from epilot360/icons icon set)
	Icon *string `json:"icon,omitempty"`
	// HEX Color code for the taxonomy
	Color *string `json:"color,omitempty"`
	// Whether the taxonomy is enabled or not
	Enabled *bool `json:"enabled,omitempty"`
	// Position of the taxonomy
	Order *float64 `json:"order,omitempty"`
	// List of locations where the taxonomy is enabled to be used. If empty, it's enabled for all locations.
	EnabledLocations []TaxonomyLocationID `json:"enabled_locations,omitempty"`
}

func (o *TaxonomyInput) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *TaxonomyInput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TaxonomyInput) GetPlural() *string {
	if o == nil {
		return nil
	}
	return o.Plural
}

func (o *TaxonomyInput) GetIcon() *string {
	if o == nil {
		return nil
	}
	return o.Icon
}

func (o *TaxonomyInput) GetColor() *string {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *TaxonomyInput) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *TaxonomyInput) GetOrder() *float64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *TaxonomyInput) GetEnabledLocations() []TaxonomyLocationID {
	if o == nil {
		return nil
	}
	return o.EnabledLocations
}
