// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TooManyRequestsError - A generic error returned by the API
type TooManyRequestsError struct {
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
	// The error message
	Error *string `json:"error,omitempty"`
}

func (o *TooManyRequestsError) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TooManyRequestsError) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
