workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    schema:
        inputs:
            - location: https://docs.api.epilot.io/entity.yaml
        overlays:
            - location: overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/epilot/epilot/schema
targets:
    terraform:
        target: terraform
        source: schema
        output: .
