// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/operations"
	"github.com/epilot/terraform-provider-epilot-schema/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *SchemaResourceModel) RefreshFromSharedEntitySchemaItem(ctx context.Context, resp *shared.EntitySchemaItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Purpose = make([]types.String, 0, len(resp.Purpose))
		for _, v := range resp.Purpose {
			r.Purpose = append(r.Purpose, types.StringValue(v))
		}
		r.Summary = types.BoolPointerValue(resp.Summary)
		attributesResult, _ := json.Marshal(resp.Attributes)
		r.Attributes = jsontypes.NewNormalizedValue(string(attributesResult))
		r.Blueprint = types.StringPointerValue(resp.Blueprint)
		capabilitiesResult, _ := json.Marshal(resp.Capabilities)
		r.Capabilities = jsontypes.NewNormalizedValue(string(capabilitiesResult))
		r.Category = types.StringPointerValue(resp.Category)
		r.CreatedAt = types.StringPointerValue(resp.CreatedAt)
		r.Description = types.StringPointerValue(resp.Description)
		if resp.DialogConfig == nil {
			r.DialogConfig = jsontypes.NewNormalizedNull()
		} else {
			dialogConfigResult, _ := json.Marshal(resp.DialogConfig)
			r.DialogConfig = jsontypes.NewNormalizedValue(string(dialogConfigResult))
		}
		r.DocsURL = types.StringPointerValue(resp.DocsURL)
		r.Draft = types.BoolPointerValue(resp.Draft)
		if resp.EnableSetting == nil {
			r.EnableSetting = jsontypes.NewNormalizedNull()
		} else {
			enableSettingResult, _ := json.Marshal(resp.EnableSetting)
			r.EnableSetting = jsontypes.NewNormalizedValue(string(enableSettingResult))
		}
		if resp.ExplicitSearchMappings == nil {
			r.ExplicitSearchMappings = jsontypes.NewNormalizedNull()
		} else {
			explicitSearchMappingsResult, _ := json.Marshal(resp.ExplicitSearchMappings)
			r.ExplicitSearchMappings = jsontypes.NewNormalizedValue(string(explicitSearchMappingsResult))
		}
		r.FeatureFlag = types.StringPointerValue(resp.FeatureFlag)
		r.Frozen = types.BoolPointerValue(resp.Frozen)
		if resp.GroupHeadlines == nil {
			r.GroupHeadlines = jsontypes.NewNormalizedNull()
		} else {
			groupHeadlinesResult, _ := json.Marshal(resp.GroupHeadlines)
			r.GroupHeadlines = jsontypes.NewNormalizedValue(string(groupHeadlinesResult))
		}
		if resp.GroupSettings == nil {
			r.GroupSettings = jsontypes.NewNormalizedNull()
		} else {
			groupSettingsResult, _ := json.Marshal(resp.GroupSettings)
			r.GroupSettings = jsontypes.NewNormalizedValue(string(groupSettingsResult))
		}
		r.Icon = types.StringPointerValue(resp.Icon)
		r.ID = types.StringPointerValue(resp.ID)
		r.Latest = types.BoolPointerValue(resp.Latest)
		if resp.LayoutSettings == nil {
			r.LayoutSettings = jsontypes.NewNormalizedNull()
		} else {
			layoutSettingsResult, _ := json.Marshal(resp.LayoutSettings)
			r.LayoutSettings = jsontypes.NewNormalizedValue(string(layoutSettingsResult))
		}
		r.Name = types.StringValue(resp.Name)
		r.Plural = types.StringValue(resp.Plural)
		r.Published = types.BoolPointerValue(resp.Published)
		r.Slug = types.StringValue(resp.Slug)
		r.TitleTemplate = types.StringPointerValue(resp.TitleTemplate)
		if resp.UIConfig == nil {
			r.UIConfig = jsontypes.NewNormalizedNull()
		} else {
			uiConfigResult, _ := json.Marshal(resp.UIConfig)
			r.UIConfig = jsontypes.NewNormalizedValue(string(uiConfigResult))
		}
		r.UpdatedAt = types.StringPointerValue(resp.UpdatedAt)
		r.Version = types.Int64PointerValue(resp.Version)
	}

	return diags
}

func (r *SchemaResourceModel) ToOperationsDeleteSchemaRequest(ctx context.Context) (*operations.DeleteSchemaRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var slug string
	slug = r.Slug.ValueString()

	out := operations.DeleteSchemaRequest{
		Slug: slug,
	}

	return &out, diags
}

func (r *SchemaResourceModel) ToOperationsGetSchemaRequest(ctx context.Context) (*operations.GetSchemaRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var slug string
	slug = r.Slug.ValueString()

	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	latest := new(bool)
	if !r.Latest.IsUnknown() && !r.Latest.IsNull() {
		*latest = r.Latest.ValueBool()
	} else {
		latest = nil
	}
	out := operations.GetSchemaRequest{
		Slug:   slug,
		ID:     id,
		Latest: latest,
	}

	return &out, diags
}

func (r *SchemaResourceModel) ToOperationsPutSchemaRequest(ctx context.Context) (*operations.PutSchemaRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var slug string
	slug = r.Slug.ValueString()

	draft := new(bool)
	if !r.Draft.IsUnknown() && !r.Draft.IsNull() {
		*draft = r.Draft.ValueBool()
	} else {
		draft = nil
	}
	entitySchemaItem, entitySchemaItemDiags := r.ToSharedEntitySchemaItem(ctx)
	diags.Append(entitySchemaItemDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.PutSchemaRequest{
		Slug:             slug,
		Draft:            draft,
		EntitySchemaItem: entitySchemaItem,
	}

	return &out, diags
}

func (r *SchemaResourceModel) ToSharedEntitySchemaItem(ctx context.Context) (*shared.EntitySchemaItem, diag.Diagnostics) {
	var diags diag.Diagnostics

	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	createdAt := new(string)
	if !r.CreatedAt.IsUnknown() && !r.CreatedAt.IsNull() {
		*createdAt = r.CreatedAt.ValueString()
	} else {
		createdAt = nil
	}
	updatedAt := new(string)
	if !r.UpdatedAt.IsUnknown() && !r.UpdatedAt.IsNull() {
		*updatedAt = r.UpdatedAt.ValueString()
	} else {
		updatedAt = nil
	}
	frozen := new(bool)
	if !r.Frozen.IsUnknown() && !r.Frozen.IsNull() {
		*frozen = r.Frozen.ValueBool()
	} else {
		frozen = nil
	}
	latest := new(bool)
	if !r.Latest.IsUnknown() && !r.Latest.IsNull() {
		*latest = r.Latest.ValueBool()
	} else {
		latest = nil
	}
	summary := new(bool)
	if !r.Summary.IsUnknown() && !r.Summary.IsNull() {
		*summary = r.Summary.ValueBool()
	} else {
		summary = nil
	}
	var slug string
	slug = r.Slug.ValueString()

	version := new(int64)
	if !r.Version.IsUnknown() && !r.Version.IsNull() {
		*version = r.Version.ValueInt64()
	} else {
		version = nil
	}
	blueprint := new(string)
	if !r.Blueprint.IsUnknown() && !r.Blueprint.IsNull() {
		*blueprint = r.Blueprint.ValueString()
	} else {
		blueprint = nil
	}
	featureFlag := new(string)
	if !r.FeatureFlag.IsUnknown() && !r.FeatureFlag.IsNull() {
		*featureFlag = r.FeatureFlag.ValueString()
	} else {
		featureFlag = nil
	}
	var name string
	name = r.Name.ValueString()

	var plural string
	plural = r.Plural.ValueString()

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	docsURL := new(string)
	if !r.DocsURL.IsUnknown() && !r.DocsURL.IsNull() {
		*docsURL = r.DocsURL.ValueString()
	} else {
		docsURL = nil
	}
	category := new(string)
	if !r.Category.IsUnknown() && !r.Category.IsNull() {
		*category = r.Category.ValueString()
	} else {
		category = nil
	}
	published := new(bool)
	if !r.Published.IsUnknown() && !r.Published.IsNull() {
		*published = r.Published.ValueBool()
	} else {
		published = nil
	}
	draft := new(bool)
	if !r.Draft.IsUnknown() && !r.Draft.IsNull() {
		*draft = r.Draft.ValueBool()
	} else {
		draft = nil
	}
	icon := new(string)
	if !r.Icon.IsUnknown() && !r.Icon.IsNull() {
		*icon = r.Icon.ValueString()
	} else {
		icon = nil
	}
	titleTemplate := new(string)
	if !r.TitleTemplate.IsUnknown() && !r.TitleTemplate.IsNull() {
		*titleTemplate = r.TitleTemplate.ValueString()
	} else {
		titleTemplate = nil
	}
	purpose := make([]string, 0, len(r.Purpose))
	for purposeIndex := range r.Purpose {
		purpose = append(purpose, r.Purpose[purposeIndex].ValueString())
	}
	var enableSetting interface{}
	if !r.EnableSetting.IsUnknown() && !r.EnableSetting.IsNull() {
		_ = json.Unmarshal([]byte(r.EnableSetting.ValueString()), &enableSetting)
	}
	var attributes interface{}
	_ = json.Unmarshal([]byte(r.Attributes.ValueString()), &attributes)
	var capabilities interface{}
	_ = json.Unmarshal([]byte(r.Capabilities.ValueString()), &capabilities)
	var groupSettings interface{}
	if !r.GroupSettings.IsUnknown() && !r.GroupSettings.IsNull() {
		_ = json.Unmarshal([]byte(r.GroupSettings.ValueString()), &groupSettings)
	}
	var groupHeadlines interface{}
	if !r.GroupHeadlines.IsUnknown() && !r.GroupHeadlines.IsNull() {
		_ = json.Unmarshal([]byte(r.GroupHeadlines.ValueString()), &groupHeadlines)
	}
	var uiConfig interface{}
	if !r.UIConfig.IsUnknown() && !r.UIConfig.IsNull() {
		_ = json.Unmarshal([]byte(r.UIConfig.ValueString()), &uiConfig)
	}
	var layoutSettings interface{}
	if !r.LayoutSettings.IsUnknown() && !r.LayoutSettings.IsNull() {
		_ = json.Unmarshal([]byte(r.LayoutSettings.ValueString()), &layoutSettings)
	}
	var dialogConfig interface{}
	if !r.DialogConfig.IsUnknown() && !r.DialogConfig.IsNull() {
		_ = json.Unmarshal([]byte(r.DialogConfig.ValueString()), &dialogConfig)
	}
	var explicitSearchMappings interface{}
	if !r.ExplicitSearchMappings.IsUnknown() && !r.ExplicitSearchMappings.IsNull() {
		_ = json.Unmarshal([]byte(r.ExplicitSearchMappings.ValueString()), &explicitSearchMappings)
	}
	out := shared.EntitySchemaItem{
		ID:                     id,
		CreatedAt:              createdAt,
		UpdatedAt:              updatedAt,
		Frozen:                 frozen,
		Latest:                 latest,
		Summary:                summary,
		Slug:                   slug,
		Version:                version,
		Blueprint:              blueprint,
		FeatureFlag:            featureFlag,
		Name:                   name,
		Plural:                 plural,
		Description:            description,
		DocsURL:                docsURL,
		Category:               category,
		Published:              published,
		Draft:                  draft,
		Icon:                   icon,
		TitleTemplate:          titleTemplate,
		Purpose:                purpose,
		EnableSetting:          enableSetting,
		Attributes:             attributes,
		Capabilities:           capabilities,
		GroupSettings:          groupSettings,
		GroupHeadlines:         groupHeadlines,
		UIConfig:               uiConfig,
		LayoutSettings:         layoutSettings,
		DialogConfig:           dialogConfig,
		ExplicitSearchMappings: explicitSearchMappings,
	}

	return &out, diags
}
