// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ListItem struct {
	QuickActions      []EntityAction      `tfsdk:"quick_actions"`
	SummaryAttributes []SummaryAttributes `tfsdk:"summary_attributes"`
}
