// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

type CreateView struct {
	Default  *EntityDefaultCreate `tfsdk:"default" tfPlanOnly:"true"`
	Disabled *EntityViewDisabled  `tfsdk:"disabled" tfPlanOnly:"true"`
	Redirect *RedirectEntityView  `tfsdk:"redirect" tfPlanOnly:"true"`
}
