// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityDefaultEdit struct {
	SearchParams      map[string]types.String `tfsdk:"search_params"`
	SummaryAttributes []types.String          `tfsdk:"summary_attributes"`
	ViewType          types.String            `tfsdk:"view_type"`
}
