// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityViewDisabled struct {
	ViewType types.String `tfsdk:"view_type"`
}
