// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityDefaultTableOptions struct {
	Label  types.String                         `tfsdk:"label"`
	Params *AddressRelationAttributeConstraints `tfsdk:"params"`
}
