// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

type EntitySchemaEditView struct {
	EntityDefaultEdit  *EntityDefaultEdit  `tfsdk:"entity_default_edit" tfPlanOnly:"true"`
	EntityViewDisabled *EntityViewDisabled `tfsdk:"entity_view_disabled" tfPlanOnly:"true"`
	RedirectEntityView *RedirectEntityView `tfsdk:"redirect_entity_view" tfPlanOnly:"true"`
}
