// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

type EntitySchemaUIConfig struct {
	CreateView *EntitySchemaCreateView `tfsdk:"create_view"`
	EditView   *EntitySchemaEditView   `tfsdk:"edit_view"`
	ListItem   *EntitySchemaListItem   `tfsdk:"list_item"`
	Sharing    *EntitySchemaSharing    `tfsdk:"sharing"`
	SingleView *EntitySchemaEditView   `tfsdk:"single_view"`
	TableView  *EntitySchemaTableView  `tfsdk:"table_view"`
}
