// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type GroupHeadline struct {
	Manifest      []types.String `tfsdk:"manifest"`
	Purpose       []types.String `tfsdk:"purpose"`
	Divider       types.String   `tfsdk:"divider"`
	EnableDivider types.Bool     `tfsdk:"enable_divider"`
	Group         types.String   `tfsdk:"group"`
	ID            types.String   `tfsdk:"id"`
	Label         types.String   `tfsdk:"label"`
	Layout        types.String   `tfsdk:"layout"`
	Name          types.String   `tfsdk:"name"`
	Order         types.Int64    `tfsdk:"order"`
	Type          types.String   `tfsdk:"type"`
}
