// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InfoTooltipTitle struct {
	Default types.String `tfsdk:"default"`
	Key     types.String `tfsdk:"key"`
}
