// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type MultiSelectAttributeOptions2 struct {
	Title types.String `tfsdk:"title"`
	Value types.String `tfsdk:"value"`
}
