// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NavbarActions struct {
	Options []EntityDefaultTableOptions `tfsdk:"options"`
	Type    types.String                `tfsdk:"type"`
}
