// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type RelationAttributeSummaryFields struct {
	Str          types.String  `queryParam:"inline" tfsdk:"str" tfPlanOnly:"true"`
	SummaryField *SummaryField `queryParam:"inline" tfsdk:"summary_field" tfPlanOnly:"true"`
}
