// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SearchMappings struct {
	Fields map[string]jsontypes.Normalized `tfsdk:"fields"`
	Index  types.Bool                      `tfsdk:"index"`
	Type   types.String                    `tfsdk:"type"`
}
