// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Sharing struct {
	ShowSharingButton types.Bool `tfsdk:"show_sharing_button"`
}
