// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SummaryAttributes struct {
	Str              types.String      `queryParam:"inline" tfsdk:"str" tfPlanOnly:"true"`
	SummaryAttribute *SummaryAttribute `queryParam:"inline" tfsdk:"summary_attribute" tfPlanOnly:"true"`
}
