// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SummaryAttribute struct {
	FeatureFlag     types.String  `tfsdk:"feature_flag"`
	Label           types.String  `tfsdk:"label"`
	RenderCondition types.String  `tfsdk:"render_condition"`
	SettingsFlag    []SettingFlag `tfsdk:"settings_flag"`
	ShowAsTag       types.Bool    `tfsdk:"show_as_tag"`
	TagColor        types.String  `tfsdk:"tag_color"`
	Value           types.String  `tfsdk:"value"`
}
