// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TableAttributeColumnHeader struct {
	Start    types.Int64  `tfsdk:"start"`
	Template types.String `tfsdk:"template"`
}
