// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetSchemaAttributeRequest struct {
	// Schema Slug and the Attribute ID
	CompositeID string `pathParam:"style=simple,explode=false,name=composite_id"`
}

func (o *GetSchemaAttributeRequest) GetCompositeID() string {
	if o == nil {
		return ""
	}
	return o.CompositeID
}

type GetSchemaAttributeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	BaseAttribute *shared.BaseAttribute
}

func (o *GetSchemaAttributeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSchemaAttributeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSchemaAttributeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSchemaAttributeResponse) GetBaseAttribute() *shared.BaseAttribute {
	if o == nil {
		return nil
	}
	return o.BaseAttribute
}
